### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by clovis1122** [chamuel51/react-BurgerBuilder#1]
What do you think about using typescript for this @chamuel51?

**Comment by chamuel51** [comment]
I was thinking about handle 

> What do you think about using typescript for this @chamuel51?

I was thinking about starting using typescript in future projects. I'm aware of those runtime errors. But now I'm just learning some concepts in React.js. Later I'm going to

**Comment by clovis1122** [comment]
Alright, cool! Looking forward to seeing what you come up with in the future.
